// ─────────────────────────────────────────────────────────────────────────────
// @finrep/db — generated Prisma client + JSONB payload types.
//
// The PrismaClient is generated by `prisma generate` into @prisma/client.
// Consumers (apps/api PrismaService) extend PrismaClient from here so there is
// a single import surface for the DB layer.
// ─────────────────────────────────────────────────────────────────────────────
export * from '@prisma/client'
export { PrismaClient, Prisma } from '@prisma/client'

// Strongly-typed shapes for the JSONB columns (rows / payload / chart / entries).
export type {
  ImportRowsJson,
  ImportMetadataJson,
  MappingEntriesJson,
  StandardChartJson,
  StatementPayloadJson,
  AuditMetadataJson,
} from './json-types.js'
