import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { describe, expect, it } from 'vitest'
import { Prisma } from '@finrep/db'
import type { PrismaService } from '../prisma/prisma.service.js'
import {
  FIXED_ASOF,
  FIXTURE_PLAN_ID,
  FIXTURE_SCHOOL_ID,
  GOLDEN_FILES,
  buildFixture,
} from './__fixtures__/generate-phase-g-golden.js'

// ─────────────────────────────────────────────────────────────────────────────
// AIC Phase G COMMIT 1 — "THE RENAME AND THE EXTRACTION CHANGE NOTHING",
// MADE FALSIFIABLE.
//
// THE ORDERING IS THE PROOF. Both goldens were generated by
// `__fixtures__/generate-phase-g-golden.ts` against UNMODIFIED origin/main, BEFORE
// the Prisma model rename and before `rollUpInitiatives` was extracted out of
// `computeForPlan`. From that moment they are read-only. A baseline regenerated
// after the change proves only that the change agrees with itself.
//
// THE FIXTURE HAS SUBSTANCE, AND THAT IS NOT DECORATION. The dev database holds
// 0 strategy goals and 0 strategy initiatives; a byte-identity assertion over an
// empty plan passes against almost any refactor, including one that breaks every
// initiative on a real school. So the golden is taken over a CONSTRUCTED plan of
// 2 pillars / 6 goals / 8 initiatives, and the roster below states exactly which
// code paths that buys — because a path the fixture does not exercise is a path
// this spec does not cover, and saying so is the difference between a golden and
// a decoration.
//
// TWO GOLDENS, ONE FIXTURE BUILDER: with a statement snapshot (the metric goals
// resolve real numbers) and without one (period === null → empty metric map,
// dataAsOf null, every metric goal falls to no_data). The second exists because
// the snapshot-absent branch is a different traversal of the same code.
//
// TWO ASSERTIONS PER GOLDEN, deliberately: `toEqual` for a readable diff, and a
// raw STRING comparison against the file bytes. The string one is strictly
// stronger — it also catches a refactor that changes KEY ORDER, which is exactly
// what moving a block of object-literal construction into a helper can do and
// what `toEqual` is blind to.
// ─────────────────────────────────────────────────────────────────────────────

const FIXTURE_DIR = fileURLToPath(new URL('./__fixtures__/', import.meta.url))

function readGolden(file: string): { text: string; parsed: unknown } {
  const text = readFileSync(`${FIXTURE_DIR}${file}`, 'utf8')
  return { text, parsed: JSON.parse(text) as unknown }
}

async function compute(hasSnapshot: boolean) {
  const { svc, goalUpdates } = buildFixture({ hasSnapshot })
  const payload = await svc.computeForPlan(FIXTURE_SCHOOL_ID, FIXTURE_PLAN_ID, FIXED_ASOF)
  return { payload, goalUpdates }
}

describe('Phase G commit 1 — the /strategy payload is byte-identical', () => {
  it('WITH a statement snapshot', async () => {
    const { payload } = await compute(true)
    const golden = readGolden(GOLDEN_FILES.snapshot)
    expect(JSON.parse(JSON.stringify(payload))).toEqual(golden.parsed)
    // Byte identity, key order included.
    expect(`${JSON.stringify(payload, null, 2)}\n`).toBe(golden.text)
  })

  it('WITHOUT a statement snapshot (period null → empty metric map, dataAsOf null)', async () => {
    const { payload } = await compute(false)
    const golden = readGolden(GOLDEN_FILES.nosnapshot)
    expect(JSON.parse(JSON.stringify(payload))).toEqual(golden.parsed)
    expect(`${JSON.stringify(payload, null, 2)}\n`).toBe(golden.text)
  })

  it('a missing/foreign plan still returns { hasPlan:false } and never throws', async () => {
    const { svc } = buildFixture({ hasSnapshot: true })
    await expect(svc.computeForPlan(FIXTURE_SCHOOL_ID, 'not-this-plan')).resolves.toEqual({
      hasPlan: false,
    })
    // Same plan id, WRONG tenant — the tenant gate, not just a missing row.
    await expect(svc.computeForPlan('another-school', FIXTURE_PLAN_ID)).resolves.toEqual({
      hasPlan: false,
    })
  })
})

describe('Phase G commit 1 — the side effect the golden cannot see', () => {
  // computeForPlan's ONE write is the persist-on-first-read baseline backfill.
  // It is invisible in the returned payload (the payload only shows the frozen
  // number), so byte-identity alone would let a refactor drop the write entirely.
  it('backfills exactly the ONE unfrozen metric goal, with the period end date', async () => {
    const { goalUpdates } = await compute(true)
    expect(goalUpdates).toHaveLength(1)
    const call = goalUpdates[0]
    expect(call.where.id).toBe('ffffffff-0000-4000-8000-000000000002') // A/G2, baseline null
    const data = call.data as {
      baselineValue: Prisma.Decimal
      baselineDate: Date
      baselineMetricPeriodId: string
    }
    // months_operating_reserve = 500_000 / (950_000 / 12)
    expect(Number(data.baselineValue)).toBeCloseTo(500_000 / (950_000 / 12), 9)
    expect(data.baselineDate.toISOString()).toBe('2026-06-30T00:00:00.000Z')
    expect(data.baselineMetricPeriodId).toBe('period-2026')
  })

  it('writes NOTHING when there is no snapshot — a missing reading is never a baseline', async () => {
    const { goalUpdates } = await compute(false)
    expect(goalUpdates).toEqual([])
  })

  it('never rewrites a FROZEN baseline (A/G1 keeps 0.01 while current is 0.05)', async () => {
    const { payload, goalUpdates } = await compute(true)
    if (!payload.hasPlan) throw new Error('expected a plan')
    const g1 = payload.pillars[0].goals[0]
    expect(g1.baseline).toBe(0.01)
    expect(g1.current).toBeCloseTo(0.05, 9)
    expect(goalUpdates.map((c) => c.where.id)).not.toContain(g1.id)
  })
})

describe('Phase G commit 1 — the roster of paths the golden actually covers', () => {
  // Stated as ASSERTIONS rather than as a comment, so a fixture edit that quietly
  // stops exercising a branch fails here instead of silently narrowing the golden.
  it('exercises every pace verdict, every initiative status, and both ownerName branches', async () => {
    const { payload } = await compute(true)
    if (!payload.hasPlan) throw new Error('expected a plan')
    const goals = payload.pillars.flatMap((p) => p.goals)

    // Two pillars, six goals, all four goal types.
    expect(payload.pillars).toHaveLength(2)
    expect(goals).toHaveLength(6)
    expect(new Set(goals.map((g) => g.goalType))).toEqual(
      new Set(['metric', 'milestone', 'task_rollup', 'manual']),
    )

    // ALL FIVE PaceStatus outcomes.
    expect(new Set(goals.map((g) => g.paceStatus))).toEqual(
      new Set(['achieved', 'behind', 'no_data', 'on_track', 'at_risk']),
    )
    // …including the overshoot flag, which is a separate field from `achieved`.
    expect(goals.filter((g) => g.overshoot)).toHaveLength(1)

    // EVERY InitiativeStatusCounts key non-zero in ONE counts object.
    const counts = goals[0].initiativeStatusCounts
    for (const k of ['planned', 'in_progress', 'blocked', 'done', 'cancelled'] as const) {
      expect(counts[k], `initiativeStatusCounts.${k} is not exercised`).toBeGreaterThan(0)
    }

    // ownerName: full-name branch AND the email fallback, both observable.
    const staleOwners = payload.summary.staleInitiatives.map((s) => s.ownerName)
    expect(staleOwners).toContain('Jo Ruiz')
    expect(staleOwners).toContain('ops@fixture.test')

    // Stale detection with its STATUS GUARD: three open rows over the threshold
    // are stale; a `done` row 90 days old and a `cancelled` row 200 days old are
    // not. If the guard were dropped, this would read 5.
    expect(payload.summary.staleInitiativeCount).toBe(3)
    expect(payload.summary.staleInitiatives.map((s) => s.staleDays)).toEqual([120, 90, 75])
    expect(payload.summary.staleInitiatives.map((s) => s.status)).not.toContain('done')
    expect(payload.summary.staleInitiatives.map((s) => s.status)).not.toContain('cancelled')

    // The behind-goal sort is pctToTarget ASCENDING, and two behind goals with
    // different fractions are required for it to be observable at all.
    expect(payload.summary.behindPaceGoals).toHaveLength(2)
    expect(payload.summary.behindPaceGoals[0].metricKey).toBe('months_operating_reserve')

    // coerceMilestones' drop branches: six raw entries in, four out.
    const milestoneGoal = goals.find((g) => g.goalType === 'milestone')!
    expect(milestoneGoal.milestones).toHaveLength(4)
    // …and the id←label fallback for the entry that carried no id.
    expect(milestoneGoal.milestones!.map((m) => m.id)).toContain('Board briefed')

    // The task groupBy rollup, including its null-sourceRef skip (a row counting
    // 9 tasks against a null ref must not reach any goal).
    const taskGoal = goals.find((g) => g.goalType === 'task_rollup')!
    expect(taskGoal.linkedTaskCounts).toEqual({ total: 5, done: 2 })

    // A metric whose MetricResult.available is false reads no_data and formats
    // to null — it never fabricates a zero.
    const unavailable = goals.find((g) => g.metricKey === 'enrollment_vs_plan')!
    expect(unavailable.current).toBeNull()
    expect(unavailable.formattedCurrent).toBeNull()
    expect(unavailable.paceStatus).toBe('no_data')
    // …and its null startDate fell back to the PLAN's start date.
    expect(unavailable.startDate).toBe('2026-07-01')

    // meanFraction with a null in the list (pillar A: 1, 0, null → 0.5).
    expect(payload.pillars[0].progressPct).toBe(0.5)
    // worstPace, and tallyGoal's six counters across the two pillars.
    expect(payload.pillars[0].goalCounts).toEqual({
      total: 3, onTrack: 0, atRisk: 0, behind: 1, achieved: 1, noData: 1,
    })
    expect(payload.pillars[1].goalCounts).toEqual({
      total: 3, onTrack: 1, atRisk: 1, behind: 1, achieved: 0, noData: 0,
    })
    expect(payload.summary.reviewDueThisMonth).toBe(true)
  })
})

describe('Phase G — /strategy is structurally blind to a goal-less initiative', () => {
  // Acceptance 2 depends on this: after commit 2 an initiative may carry
  // goalId = null, and `/strategy` must not change because of it. It cannot —
  // computeForPlan reaches initiatives ONLY by walking
  // plan.pillars[].goals[].initiatives[], so a row with no goal is unreachable by
  // construction rather than by a filter someone could delete.
  //
  // Asserted two ways: over the SOURCE (the traversal is the only reader), and
  // functionally (a school-scoped row that is not in the tree cannot move the
  // payload, because nothing ever queries for one).
  it('computeForPlan reads initiatives only through the plan tree', () => {
    const src = readFileSync(
      fileURLToPath(new URL('./strategy-progress.service.ts', import.meta.url)),
      'utf8',
    )
    // No flat, school-scoped initiative query anywhere in the progress spine.
    expect(src).not.toMatch(/(strategy|improvement)Initiative\s*\.\s*findMany/)
    expect(src).not.toMatch(/(strategy|improvement)Initiative\s*\.\s*findFirst/)
  })

  it('a goal-less row in the same school leaves the payload unmoved', async () => {
    // The double answers the plan query as usual; a goal-less initiative exists
    // in the school but belongs to no goal, so the tree never yields it.
    const withGoalless = await computeWithExtraGoallessRow()
    const golden = readGolden(GOLDEN_FILES.snapshot)
    expect(`${JSON.stringify(withGoalless, null, 2)}\n`).toBe(golden.text)
  })
})

/**
 * Re-run the fixture with an extra school-scoped, goal-LESS initiative present in
 * the (mocked) database. It is deliberately not attached to any goal in the plan
 * tree, which is exactly the shape commit 2 introduces.
 */
async function computeWithExtraGoallessRow() {
  const { svc } = buildFixture({ hasSnapshot: true })
  // The goal-less row would only ever be reachable through a flat query, and the
  // task rollup is the one place a stray sourceRef could leak in — so feed it one
  // and prove it lands nowhere.
  const prisma = (svc as unknown as { prisma: PrismaService }).prisma as unknown as {
    task: { groupBy: () => Promise<unknown[]> }
  }
  const original = prisma.task.groupBy
  prisma.task.groupBy = async () => [
    ...((await original()) as unknown[]),
    { sourceRef: 'gggggggg-0000-4000-8000-00000000000f', status: 'done', _count: { _all: 7 } },
  ]
  return svc.computeForPlan(FIXTURE_SCHOOL_ID, FIXTURE_PLAN_ID, FIXED_ASOF)
}
